In [9]:
import pandas as pd

In [10]:
dataset1 = pd.read_csv("X:/AI-SPAM-PHISHING-DETECTOR/data/processed/email_spam_cleaned.csv")

dataset2 = pd.read_csv("X:/AI-SPAM-PHISHING-DETECTOR/data/processed/personal_emails_cleaned.csv")

dataset3 = pd.read_csv("X:/AI-SPAM-PHISHING-DETECTOR/data/processed/spamassassin_cleaned.csv")

In [11]:
print("Dataset 1 :", dataset1.shape)
print("Dataset 2 :", dataset2.shape)
print("Dataset 3 :", dataset3.shape)

Dataset 1 : (83, 6)
Dataset 2 : (475, 3)
Dataset 3 : (5293, 3)

In [13]:
# Dataset 1
dataset1 = dataset1[["title", "text", "type"]]

# Dataset 2
dataset2 = dataset2[["title", "text", "type"]]

# Dataset 3
dataset3 = dataset3[["title", "text", "type"]]

In [14]:
final_df = pd.concat(
    [
        dataset1,
        dataset2,
        dataset3
    ],
    ignore_index=True
)

In [15]:
print(final_df["type"].value_counts())

type
not spam    4425
spam        1426
Name: count, dtype: int64

In [16]:
final_df

,title,text,type
0,?? the secrets to SUCCESS,"Hi James,\n\nHave you claim your complimentary...",spam
1,?? You Earned 500 GCLoot Points,"\nalt_text\nCongratulations, you just earned\n...",not spam
2,?? Your GitHub launch code,"Here's your GitHub launch code, @Mortyj420!\n ...",not spam
3,[The Virtual Reward Center] Re: ** Clarifications,"Hello,\n \nThank you for contacting the Virtua...",not spam
4,"10-1 MLB Expert Inside, Plus Everything You Ne...","Hey Prachanda Rawal,\n\nToday's newsletter is ...",spam
...,...,...,...
5846,NaN,----------------------------------------------...,not spam
5847,NaN,"EFFector Vol. 15, No. 35 November ...",not spam
5848,NaN,\nWe have extended our Free seat sale until Th...,not spam
5849,NaN,___ ___ ...,not spam
5850,NaN,IN THIS ISSUE:01. Readers write\n02. Extension...,not spam

In [17]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5851 entries, 0 to 5850
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   558 non-null    object
 1   text    5851 non-null   object
 2   type    5851 non-null   object
dtypes: object(3)
memory usage: 137.3+ KB

In [21]:
# Save by overwriting the old file
final_df.to_csv("X:/AI-SPAM-PHISHING-DETECTOR/data/processed/final_dataset.csv", index=False)

print("✅ Final dataset updated successfully!")
print("Shape:", final_df.shape)
print("\nClass Distribution:")
print(final_df["type"].value_counts())

✅ Final dataset updated successfully!
Shape: (5851, 3)

Class Distribution:
type
not spam    4425
spam        1426
Name: count, dtype: int64

In [22]:
final_df.info()
final_df.isnull().sum()
final_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5851 entries, 0 to 5850
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   558 non-null    object
 1   text    5851 non-null   object
 2   type    5851 non-null   object
dtypes: object(3)
memory usage: 137.3+ KB

,title,text,type
0,?? the secrets to SUCCESS,"Hi James,\n\nHave you claim your complimentary...",spam
1,?? You Earned 500 GCLoot Points,"\nalt_text\nCongratulations, you just earned\n...",not spam
2,?? Your GitHub launch code,"Here's your GitHub launch code, @Mortyj420!\n ...",not spam
3,[The Virtual Reward Center] Re: ** Clarifications,"Hello,\n \nThank you for contacting the Virtua...",not spam
4,"10-1 MLB Expert Inside, Plus Everything You Ne...","Hey Prachanda Rawal,\n\nToday's newsletter is ...",spam

In [23]:
final_df["title"] = final_df["title"].fillna("")

In [24]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5851 entries, 0 to 5850
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   5851 non-null   object
 1   text    5851 non-null   object
 2   type    5851 non-null   object
dtypes: object(3)
memory usage: 137.3+ KB

In [25]:
final_df.to_csv("X:/AI-SPAM-PHISHING-DETECTOR/data/processed/final_dataset.csv", index=False)

print("✅ final_dataset.csv saved successfully!")

✅ final_dataset.csv saved successfully!

In [26]:
final_df["title"].isnull().sum()

np.int64(0)

In [27]:
final_df.to_csv("X:/AI-SPAM-PHISHING-DETECTOR/data/processed/final_dataset.csv", index=False)